### ISSUE TITLE
`Error: raw_definition property '/x-topics/0/content' is not of type: string` with x-topics external markdown

### ISSUE THREAD

**Issue by awarrenlove** [bump-sh/cli#220]
I am looking into using Bump as a documentation system for the new API my company is building, and I'm running into an error whenever I attempt to reference an external Markdown file in a topic.

I have `"bump-preview": "bump preview resources/openapi/openapi.yaml"` defined in my package.json scripts, so when I run `yarn bump-preview` I see this output.

```
$ yarn bump-preview
yarn run v1.22.5
$ bump preview resources/openapi/openapi.yaml
* Let's render a preview on Bump... !
 ›   Error: raw_definition property '/x-topics/0/content' is not of type: string
error Command failed with exit code 122.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
yarn run v1.22.5
$ bump preview resources/openapi/openapi.yaml
* Let's render a preview on Bump... !
 ›   Error: raw_definition property '/x-topics/0/content' is not of type: string
error Command failed with exit code 122.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

The entirety of my openapi.yaml file is

```
openapi: 3.1.0
info:
  title: Bump CLI
  version: dev
  description: Test bump-cli
x-topics:
  - title: Test Markdown
    content:
      $ref: '../docs/test.md'
paths: {}
```

as I wanted to keep things minimal for this report, and the markdown file located at `../docs/test.md` relative to that file is

```
# External Markdown

Some external markdown file.
```

If I change the path to an invalid location, it gives me an appropriate file-not-found error, so it appears to be finding the file correctly. Also, if I put that exact Markdown directly in the yaml file it previews correctly, so there appears to be some issue with the output of the Markdown parser.

**Comment by paulRbr** [comment]
Hi @awarrenlove, thanks for the report. We indeed have a nasty bug in the specification validation. Let me take a look and I will come back when this is fixed on our side.

**Comment by paulRbr** [comment]
Hi again @awarrenlove, we have pushed a fix to our validation rules.
Your should now be able to send an API definition file with `x-topics` referencing external markdown files.

Thanks a lot for taking the time to report the issue and sorry for the inconvenience caused with this!

If you need anything more please let me know, for now I'll close this issue.

**Comment by awarrenlove** [comment]
Perfect! I was able to confirm that it works for me. Thank you for the quick response!
