### ISSUE TITLE
$ref not working on windows

### ISSUE THREAD

**Issue by deka** [bump-sh/cli#361]
Hi,

Step to reproduce : 
A folder with two files : 
- topic.md
- spec.json _(spec OpenAPI)_

in spec.jons : 
```
...
"x-topics": [
    {
      "title": "A topic",
      "content": {
            "$ref": "./topic.md"
    }
  ]
...
```

With cli : 
`/> bump preview`

Result : topic.md not  merged

**Comment by scharrier** [comment]
Thanks for the issue @deka, we are finalizing a fix here: https://github.com/bump-sh/cli/pull/360#pullrequestreview-1142318254

**Comment by deka** [comment]
@paulRbr , @scharrier 

 bump-cli/2.4.1 work fine if markdown is in directory but not in parrent directory

./topic.md -> ok
../topic.md -> not ok
./../topic.md -> not ok

**Comment by paulRbr** [comment]
> @paulRbr , @scharrier
> 
> bump-cli/2.4.1 work fine if markdown is in directory but not in parrent directory
> 
> ./topic.md -> ok ../topic.md -> not ok ./../topic.md -> not ok

Hi again @deka, thanks a lot for taking the time to share this issue. We have fixed another bug in our backend code this time so this should work as expected on windows related CLI executions.

Please let us know if you have any other needs/questions. Thanks!
