### ISSUE TITLE
Multiple security headers not displayed in curl examples

### ISSUE THREAD

**Issue by deka** [bump-sh/cli#366]
Hi,
I'm trying to define JWT and API key  security.
Only first security schemes is displayed ith `bump preview`
My spec looks like : 
```json
...
 "components": {
    "securitySchemes": {
      "my_jwt": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      },
      "my_api_key": {
        "type": "apiKey",
        "name": "Ocp-Apim-Subscription-Key",
        "in": "header"
      }
    }
}
...
...
"security": [
    {
      "my_jwt": [],
      "my_api_key": []
    }
  ]
...
```

Actual result : 
```bash
curl \
 -X GET https://{uri} \
 -H "Authorization: Bearer $ACCESS_TOKEN"
```

Expected : 
```bash
curl \
 -X GET https://{uri} \
 -H "Authorization: Bearer $ACCESS_TOKEN" \
 -H "Ocp-Apim-Subscription-Key: $API_KEY"
```

**Comment by paulRbr** [comment]
Hi @deka,

Thanks a lot for the feedback. We are taking a look on this and will let you know how to fix this as soon as possible.

**Comment by paulRbr** [comment]
Hello @deka,

sorry for the late reply. We have deployed a fix for this issue on bump.sh. Can you let me know if the result suits you?

Thank you :slightly_smiling_face:

**Comment by deka** [comment]
Thanks @paulRbr, it works as expected.
Regards
