### ISSUE TITLE
False detection of changes 

### ISSUE THREAD

**Issue by ad-m-ss** [bump-sh/cli#370]
Hi,

I would like use bump-cli to track changes in specification. However I notice that there is a noise changes detected.

```
$ npm list  | grep 'bump-cli'
└── bump-cli@2.4.1
$ curl "https://api.production.selectstar.com/swagger/?format=openapi" | jq '.' > ./remote-openapi.json
...
$ ./node_modules/.bin/bump diff remote-openapi.json remote-openapi.json
* Comparing the two given definition files... done
[Breaking] Modified: PATCH /tags/{guid}/
  [Breaking] Body modified
    Attributes added: guid, name, description, richtext_description, icon, color, parent, ordinal, updated_on, owner, breadcrumbs, visible
    [Breaking] Attribute removed: items
  [Breaking] Response modified: 200
    Attributes added: guid, name, description, richtext_description, icon, color, parent, ordinal, updated_on, owner, breadcrumbs, visible
    [Breaking] Attribute removed: items
```

I would expect that the specification compared with itself is not able to generate any differences, but it is different, so the comparison has some bugs.

Could we make avoid that noise to make comparisons & changelog more reliable?

Kind regards

**Comment by paulRbr** [comment]
Hello @ad-m-ss,

Thanks for your bug report. I took a close look to the specification file you have shared (https://api.production.selectstar.com/swagger/?format=openapi) and noticed there's an issue in the `operationId` values used. Indeed, by the openapi specification, the [“Operation object”](https://spec.openapis.org/oas/v3.1.0#operation-object) has a possible `operationId` field which is defined by:

> Unique string used to identify the operation. The id MUST be unique among all operations described in the API.

However you have two operations (`PATCH /tags/{guid}/` and `PATCH /tags/`) which have the same operation id value of `tags_partial_update`. This leads our diff computation to compare those two operations (incorrectly, yes).

I would suggest to try to fix the operation Ids from your API definition and we will try to make some changes on our side to avoid this kind of incorrect difference (We will probably ignore any operations which has a duplicate operationId).

Let me know if this helps and if you have any further questions. 
Good day to you :slightly_smiling_face:

**Comment by ad-m-ss** [comment]
Thanks for your analysis. I will fix that & keep you informed.

**Comment by ad-m-ss** [comment]
It helps! Thanks!

**Comment by ad-m-ss** [comment]
I am not sure that ignoring any operations is a good idea. I would prefer to have an error & refused that changes to be merged that silently ignore.

**Comment by paulRbr** [comment]
> I am not sure that ignoring any operations is a good idea. I would prefer to have an error & refused that changes to be merged that silently ignore.

Thanks for the feedback, that definitely sounds like a better idea. :slightly_smiling_face:
