### ISSUE TITLE
[Feature request] : Add the possibility to put an external url in the header of the documentation page (hub and spec)

### ISSUE THREAD

**Issue by deka** [bump-sh/cli#374]
Hi,
Can you look at the possibility to put a fallback url in the header of the documentation page ?
Use case : 
- I am on my portal, i go to bump documentation
- I need return to my portal

Regards

**Comment by paulRbr** [comment]
Hi @deka, thanks for you message. 

Could you clarify what you mean by a “fallback url”. Also if you could clarify what your “portal” is?

What do you wish for in the header of the documentation page between the three following:

- An external link (to a custom URL you provide as a user in the API spec)
- A link to your admin panel hosted on Bump (the page where you can configure your API documentation)
- A link to your Hub hosted on Bump (the public page listing your API documentations). _Please note that this link already exist in the header, so I guess that's not what you asked_
- Other?

Thanks!

**Comment by deka** [comment]
@paulRbr,

> Could you clarify what you mean by a “fallback url”. Also if you could clarify what your “portal” is?

The portal is my app site, an external link on the top bar does the job

**Comment by paulRbr** [comment]
Hi @deka,

I'll close this issue for now as we seem to support what you want. Please feel free to re-open if it didn't answer your needs :blush:
