### ISSUE TITLE
TimeOut Questions

### ISSUE THREAD

**Issue by blemke1971** [bump-sh/cli#558]
We have implemented this in our builds to do comparison on our documentation to detect breaking changes.   It works very well.   However every once and a while when teams have an aggressive amount of building the tool seems to break with a "try again later" error message.   I was wondering if this tool has some built in throttling in lines with the comment from your documentation here.

> You can create as many diffs as you like without being authenticated. This is a free and unlimited service provided as long as you use the service fairly. {: .info}

**Comment by paulRbr** [comment]
Hi @blemke1971,

Thanks a lot for your feedback. It would help us to understand why you get those timeouts if you could provide the two different API documents you are trying to diff when getting this error. Could you share those please?

I'll close this issue as it's the same as #555. We need to find some solutions for those timeouts and will get back on the #555 issue when we have some good news.

Thanks again for your time on reporting this, and don't forget to send be some two API documents which leads to those timeouts.
